package scanner

// knownWalletExtensions maps Chromium extension IDs to crypto wallet display names.
// Used when manifest.json has no human-readable title; scan also reads manifest on disk.
// Sources: jiayuchann targeted_extensions.csv gist, HyperHives config, MacOS-Stealer-in-Rust, curated overrides.
var knownWalletExtensions = map[string]string{
	"abkahkcbhngaebpcgfmhkoioedceoigp": "Casper Wallet",
	"abogmiocnneedmmepnohnhlijcjpcifd": "Blade Hedera Web3 Digital Wallet",
	"achbneipgfepkjolcccedghibeloocbg": "MathWallet",
	"acmacodkjbdgmoleebolmdjonilkdbch": "Rabby Wallet",
	"aeachknmefphepccionboohckonoeemg": "Coin98 Wallet Extension Crypto & Defi",
	"afbcbjpbpfadlkmhmclhkeeodmamcflc": "MathWallet",
	"aflkmfhebedbjioipglgcbcmnbpgliof": "Backpack",
	"agoakfejjabomempkjlepdflaleeobhb": "Core | Crypto Wallet & NFT Extension",
	"ahkfhobdidabdlaphghgikhlpdbnodpa": "Portis",
	"aholpfdialjgjfhomihkjbmgjidlcdno": "Exodus Web3 Wallet",
	"aiifbnbfobpmeekipheeijimdpnlpgpp": "Station Wallet",
	"aijcbedoijmgnlmjeegjaglmepbmpkpi": "Leap Terra",
	"aipfkbcoemjllnfpblejkiaogfpocjba": "Frontier Wallet",
	"alncdjedloppbablonallfbkeiknmkdi": "Crypto.com DeFi Wallet",
	"amkmjjmmflddogmhpjloimipbofnfjih": "Wombat - Gaming Wallet for Ethereum & EOS",
	"andhndehpcjpmneneealacgnmealilal": "HaHa Wallet",
	"anokgmphncpekkhclmingpimjmcooifb": "Compass Wallet for Sei",
	"aodkkagnadcbobfpggfnjeongemjbjca": "BoltX",
	"aoilkoeledabkfogmczlbdfhbdkoggko": "Titan Wallet",
	"apicngpmdlmkkjfbmdhpjedieibfklkf": "Polkadot-JS",
	"bcopgchhojmggmffilplmbdicgaihlkp": "Hycon Lite Client",
	"bdgmdoedahdcjmpmifafdhnffjinddgc": "Bittensor Wallet",
	"bfeplaecgkoeckiidkgkmlllfbaeplgm": "Radix Wallet Connector",
	"bfnaelmomeimhlpmgjnjophhpkkoljpa": "Phantom",
	"bhemafnepdahjhdibdejjdojplpanpjm": "Clover Wallet",
	"bhhhlbepdkbapadjdnnojkbgioiodbic": "Solflare Wallet",
	"bifidjkcdpgfnlbcjpdkdcnbiooooblg": "Fuelet Fuel",
	"bipdhagncpgaccgdbddmbpcabgjikfkn": "Clown Wallet",
	"blnieiiffboillknjnepogjhkgnoapac": "Equal Wallet",
	"blpcdojejhnenclebgmmbokhnccefgjm": "Defiat Wallet",
	"bmkakpenjmcpfhhjadflneinmhboecjf": "WELLDONE Wallet for multichain",
	"bocpokimicclglpgehgiebilfpejmgjo": "FoxWallet",
	"bocpokimicclpaiekenaeelehdjllofo": "XinPay",
	"bpcedbkgmedfpdpcabaghjbmhjoabgmh": "MewCX",
	"canipghmckojpianfgiklhbgpfmhjkjg": "Crossmark Wallet",
	"cdjkjpfjcofdjfbdojhdmlflffdafngk": "Opera Crypto Wallet",
	"cflgahhmjlmnjbikhakapcfkpbcmllam": "OORT Wallet",
	"cgeeodpfagjceefieflmdfphplkenlfk": "EVER Wallet",
	"cihmoadaighcejopammfbmddcmdekcje": "LeafWallet - Easy to use EOS wallet",
	"cjelfplplebdjjenllpjcblmjkfcffne": "Jaxx Liberty",
	"cjfkaebgdjmgkknhmeddmbjfkkllcfma": "Rabby Wallet",
	"cjmkndjhnagcfbpiemnkdpomccnjblmj": "Finnie",
	"cmeakgjggjdhccnmkgpjdnaefojkbgmb": "MathWallet",
	"cmndjbecilbocjfkibfbifhngkdmjgog": "Swash",
	"cnmamaachppnkjgnildpdmkaakejnhae": "Auro Wallet",
	"cnncmdhjacpkmjmkcafchppbnpnhdmon": "HAVAH Wallet",
	"cnoepnljjcacmnjnopbhjelpmfokpijm": "Kabila Wallet",
	"cphhlgmgameodnhkjdmkpanlelnlohao": "NeoLine",
	"cpmkedoipcpimgecpmgpldfpohjplkpp": "Gate Wallet",
	"dbgnhckhnppddckangcjbkjnlddbjkna": "Fin Wallet Sei",
	"dgiehkgfknklegdhekgeabnhgfjhbajd": "Komodo Wallet",
	"dkdedlpgdmmkkfjabffeganieamfklkm": "Cyano Wallet",
	"dlcobpjiigpikoobohmabehhmhfoodbb": "Argent X - Starknet Wallet",
	"dldjpboieedgcmpkchcjcbijingjcgok": "Fuel Wallet",
	"dljopojhfmopnmnfocjmaiofbbifkbfb": "Halo Wallet",
	"dmkamcknogkgcdfhhbddcghachkejeap": "Keplr",
	"dngmlblcodfobpdpecaadgfbcggfjfnm": "MultiversX Wallet",
	"eaeecbmeajhliilmacefcgjnnijkkfki": "Trust Wallet Beta",
	"ebfidpplhabeedpnhjnobghokpiioolj": "Fewcha Move Wallet",
	"efbglgofoippbgcjepnhiblaibcnclgk": "Martian Aptos & Sui Wallet Extension",
	"efnhgnhicmmnchpjldjminakkdnidbop": "Titan Wallet",
	"egjidjbpglichdcondbcbdnbeeppgdph": "Trust Wallet",
	"ehgjhhccekdedpbkifaojjaefeohnoea": "Ambire",
	"eigblbgjknlfbajkfhopmcojidlgcehm": "XMR.PT",
	"ejbalbakoplchlghecdalmeeeajnimhm": "MetaMask",
	"ejbidfepgijlcgahbmbckmnaljagjoll": "Salmon Wallet",
	"ejjladinnckdgjemekebdpeokbikhfci": "Petra Aptos Wallet",
	"ekpbnlianmehonjglfliphieffnpagjk": "Portis",
	"elalghlhoepcjfaedkcmjolahamlnjcp": "Bitgreen Wallet",
	"emeeapjkbcbpbpgaagfchmcgglmebnen": "Surf Wallet",
	"enabgbdfcbaehmbigakijjabdpdnimlg": "Manta Wallet",
	"eogjbkambcobpejogjednkhnkdlpjkgf": "ZenGo Wallet",
	"epapihdplajcdnnkdeiahlgigofloibg": "Sender Wallet",
	"fcckkdbjnoikooededlapcalpionmalo": "Mobox",
	"fcfcfllfndlomdhbehjjcoimbgofdncg": "Leap Cosmos Wallet",
	"fdcnegogpncmfejlfnffnofpngdiejii": "Razor Wallet",
	"fdgodijdfciiljpnipkplpiogcmlbmhk": "Coin98",
	"ffabmkklhbepgcgfonabamgnjfjdbjoo": "Cyano Wallet",
	"ffbceckpkpbcmgiaehlloocglmijnpmp": "Initia Wallet",
	"ffnbelfdoeiohenkjibnmadjiehjhajb": "Yoroi",
	"fgdbiimlobodfabfjjnpefkafofcojmb": "Hashpack Wallet",
	"fhbohimaelbohpjbbldcngcnapndodjp": "BEW lite",
	"fhilaheimglignddkjgofkcbgekhenbh": "Oxygen Wallet",
	"fhmfendgdocmcbmfikdcogofphimnkno": "Sollet",
	"fihkakfobkmkjojpchpfgcmhfjnmnfpi": "BitApp Wallet",
	"fijngjgcjhjmmpcmkeiomlglpeiijkld": "Talisman Wallet",
	"flhpobcpjeilaheadnpdkkinakogbdhb": "HashPass Wallet",
	"flpiciilemghbmfalicajoolhkkenfel": "ICONex",
	"fnjhmkhhmkbjkkabndcnnogagogbneec": "Ronin Wallet",
	"fnnegphlobjdpkhecapkijjdkgcjhkib": "Harmony Wallet",
	"fopmedgnkfpebgllppeddmmochcookhc": "Suku Wallet",
	"fpkhgmpbidmiogeglndfbkegfdlnajnf": "Cosmostation Wallet",
	"gafhhkghbfjjkeiendhlofajokpaflmk": "Lace",
	"ghlmndacnhlaekppcllcpcjjjomjkjpg": "Wizz Wallet",
	"ginchbkmljhldofnbjabmeophlhdldgp": "PolkaGate The gateway to the Polkadot eco.",
	"gjlmehlldlphhljhpnlddaodbjjcchai": "Nautilus Wallet",
	"gjnckgkfmgmibbkoficdidcljeaaaheg": "Atomic Wallet",
	"glmhbknppefdmpemdmjnjlinpbclokhn": "Orange Wallet",
	"hbbgbephgojikajhfbomhlmmollphcad": "Rise - Aptos Wallet",
	"hbnpcbochkgodkmmicbhfpmmkhbfbhim": "Mojito - A Mintlayer Wallet",
	"hcjhpkgbmechpabifbggldplacolbkoh": "StarKey Wallet - The official wallet for Supra",
	"heamnjbnflcikcggoiplibfommfbkjpj": "Zeal Wallet",
	"hfbglbedehonhmcljhlomlbjgmblieip": "LuckyCoin Wallet",
	"hifafgmccdpekplomjjkcfgodnhcellj": "Crypto.com | Onchain Extension",
	"hjebgbdpfgbcjdopfbbcpcjefcmhpdpn": "Loopring Wallet",
	"hmeobnfnfcmdkdcmlblgagmfpfboieaf": "Ctrl Wallet",
	"hmnminpbnkpndojhkipgkmokcocmgllb": "ZenGo Wallet",
	"hnfanknocfeofbddgcijnmhnfnkdnaad": "Coinbase Wallet extension",
	"hnhobjmcibchnmglfbldbfabcgaknlkj": "Flint Wallet",
	"hnmpcagpplmpfojmgmnngilcnanddlhb": "SafePal Wallet",
	"hpbgcgmiemanfelegbndmhieiigkackl": "Monsta Wallet",
	"hpclkefagolihohboafpheddmmgdffjm": "Flow Wallet",
	"hpglfhgfnhbgpjdenjgmdgoeiappafln": "Guarda",
	"ibnejdfjmmkpcnlpebklmnkoeoihofec": "TronLink",
	"idnnbdplmphpflfnlkomgpfbpcgelopg": "Xverse Bitcoin Crypto Wallet",
	"idpdilbfamoopcfofbipefhmmnflljfi": "FACT wallet",
	"ifckdpamphokdglkkdomedpdegcjhjdp": "ONTO Wallet",
	"iglbgmakmggfkoidiagnhknlndljlolb": "Portkey Wallet",
	"ilajcdmbpocfmipjioonlmljbmljbfpj": "Rabby Wallet",
	"ilhaljfiglknggcoegeknjghdgampffk": "Beam Web Wallet",
	"iokeahhehimjnekafflcihljlcjccdbe": "Alby - Bitcoin Wallet for Lightning & Nostr",
	"jaoafjlleohakjimhphimldpcldhamjp": "Sollet Wallet",
	"jbdaocneiiinmjbjlgalhcelgbejmnid": "Nifty Wallet",
	"jbkgjmpfammbgejcpedggoefddacbdia": "Parallel wallet",
	"jblndlipeogpafnldhgmapagcccfchpi": "Kaia Wallet",
	"jgaaimajipbpdogpdglhaphldakikgef": "Coinhub",
	"jiepnaheligkibgcjgjepjfppgbcghmp": "Doge Labs Wallet",
	"jihneinfbfkaopkpnifgbfdlfpnhgnko": "Clover Wallet",
	"jiidiaalihmmhddjgbnbgdfflelocpak": "Bitget Wallet - Crypto Web3 | Bitcoin & USDT",
	"jmchmkecamhbiokiopfpjjmfkpbbjjaf": "ONE Wallet",
	"jnldfbidonfeldmalbflbmlebbipcnle": "Bitfinity Wallet",
	"jnlgamecbpmbajjfhmmmlhejkemejdma": "Braavos Bitcoin & Starknet Wallet",
	"jnmbobjmhlngoefaiojfljckilhhlhcj": "OneKey",
	"jojhfeoedkpkglbfimdfabpdfjaoolaf": "Polymesh Wallet",
	"kbdcddcmgoplfockflacnnefaehaiocb": "Shell Wallet",
	"kdfmmohbkjggjlmelhhmcgohadhdeijn": "Hashpack Wallet",
	"kdgecbhaddlgffpdffafpikmjekjflff": "Frontier Wallet",
	"kehbljcfpanhajpidcmblpdnlphelaie": "AlphaWallet",
	"kennjipeijpeengjlogfdjkiiadhbmjl": "PWR Wallet",
	"kfdniefadaanbjodldohaedphafoffoh": "Typhon Wallet",
	"kgpidhfbnidjcldpngdonkekmpkgihke": "Solflare Wallet",
	"khpkpbbcccdmmclmpigdgddabeilkdpd": "Suiet | Sui Wallet",
	"kibokekadkmfjfckkbgndphcjejhoial": "Ambire Wallet",
	"kilnpioakcdndlodeeceffgjdpojajlo": "Aurox Wallet",
	"kjjebdkfeagdoogagbhepmbimaphnfln": "Ultra Wallet",
	"kjklkfoolpolbnklekmicilkhigclekd": "AlphaWallet",
	"kkpllkodjeloidieedojogacfhpaihoh": "Enkrypt ETH BTC and Solana Wallet",
	"klghhnkeealcohjjanjjdaeeggmfmlpl": "Zerion Wallet for Web3 & NFTs",
	"klnaejjgbibmhlephnhpmaofohgkpgkd": "ZilPay",
	"kmphdnilpmdejikjdnlbcnmnabepfgkh": "OsmWallet - Your XRP wallet.",
	"kncchdigobghenbbaddojjnnaogfppfj": "iWallet",
	"kpfopkelmapcoipemfendmdcghnegimn": "Liquality",
	"kppfdiipphfccemcignhifpjkapfbihd": "Frontier Wallet",
	"lccbohhgfkdikahanoclbdmaolidjdfl": "Wigwam",
	"ldcihfaojdpmhjkhioilfjjckehehddg": "Stamp Wallet",
	"ldinpeekobnhjjdofggfgjlcehhmanlj": "Leather",
	"lefigjhibehgfelfgnjcoodflmppomko": "Trust Wallet",
	"leibnlghpgpjigganjmbkhlmehlnaedn": "Keplr Wallet",
	"lfmmjkfllhmfmkcobchabopkcefjkoip": "LootRush Wallet",
	"lgmpcpglpngdoalbgeoldeajfclnhafa": "SafePal Extension Wallet",
	"lhkfcaflljdcedlgkgecfpfopgebhgmb": "Solflare Wallet",
	"ljfoeinjpaedjfecbmggjgodbgkmjkjk": "Trezor Wallet",
	"lkpmkhpnhknhmibgnmmhdhgdilepfghe": "Prax wallet",
	"lnehnlppemineeojdjkcpgoockkboohn": "ZelCore",
	"lnnnmfcpbkafcpgdilckhmhbkkbpkmid": "Koala Wallet",
	"loinekcabhlmhjjbocijdoimmejangoa": "Glass wallet | Sui wallet",
	"lpbfigbdccgjhflmccincdaihkmjjfgo": "Guarda Wallet",
	"lpfcbjknijpeeillifnkikgncikgfhdo": "Nami",
	"lpilbniiabackdjcionkobglmddfbcjo": "Keeper Wallet",
	"lplmibmljignbdmkclofcackoolcfnhj": "Pillar Wallet",
	"mcbpblocgmgfnpjjppndjkmgjaogfceg": "Binance Wallet",
	"mcohilncbfahbmgdjkbpemcciiolgcge": "OKX Wallet",
	"mdjmfdffdcmnoblignmgpommbefadffd": "Carax Wallet",
	"mehhoobkfknjlamaohobkhfnoheajlfi": "Bifrost Wallet",
	"mfalklfpognjpjfbfllclbfjieknodid": "Athene Wallet",
	"mfgccjchihfkkindfppnaooecgfneiii": "TokenPocket - Web3 & Crypto Wallet",
	"mfhbebgoclkghebffdldpobeajmbecfk": "Starcoin",
	"mgffkfbidcmcenlkgaebhoojfcegdndl": "MewCX",
	"mgffkfbidihjpoaomajlbgchddlicgpn": "Pali Wallet",
	"mjgkpalnahacmhkikiommfiomhjipgjn": "Reef Chain Wallet Extension",
	"mkpegjkblkkefacfnmkajcjmabijhclg": "Magic Eden Wallet",
	"mlbnicldlpdimbjdcncnklfempedeipj": "Yours Wallet",
	"mlhakagmgkmonhdonhkpjeebfphligng": "ABC Wallet",
	"mmmjbcfofconkannjonfmjjajpllddbg": "Fluvi Wallet",
	"mnfifefkajgofkcjkemidiaecocnkjeh": "TezBox - Tezos Wallet",
	"nanjmdknhkinifnkgdcggcfnhdaammmj": "Guild Wallet",
	"nebnhfamliijlghikdgcigoebonmoibm": "Leo Wallet",
	"nfinomegcaccbhchhgflladpfbajihdf": "G.U. Wallet",
	"nhdllgjlkgfnoianfjnbmcjmhdelknbm": "Blocto Wallet",
	"nhlnehondigmgckngjomcpcefcdplmgc": "Fearless Wallet",
	"nhnkbkgjikgcigadomkphalanndcapjk": "CLV Wallet",
	"nkbihfbeogaeaoehlefnkodbefgpgknn": "MetaMask",
	"nkddgncdjgjfcddamfgcmfnlhccnimig": "Saturn Wallet",
	"nknhiehlklippafakaeklbeglecifhad": "Nabox Wallet",
	"nkpfkohfaabomajpmcikkgipnddjbjlm": "XDEFI Wallet",
	"nlbmnnijcnlegkjjpcfjclmcfggfefdm": "MEW CX",
	"nlgbhdfgdhgbiamfdfmbikcdghidoadd": "Byone",
	"nlgnepoeokdfodgjkjiblkadkjbdfmgd": "Multi Wallet",
	"nopnfnlbinpfoihclomelncopjiioain": "Viction Wallet",
	"nphplpgoakhhjchkkhmiggakijnkhfnd": "TON Wallet",
	"oblahjcienboiocobpfmpkhgbilacbof": "MyEtherWallet",
	"ocjdpmoallmgmjbbogfiiaofphbjgchh": "Elli Sui",
	"odbfpeeihdkbihmopkbjmoonfanlbfcl": "MyEtherWallet",
	"oebgglckkdmdcphmbdcbdlkedjbbinii": "Sender",
	"ofhbbkphhbklhfoeikjpcbhemlocgigb": "Coinbase Wallet",
	"ohjgojhmjldjfningdelbffpnddmiphh": "NEAR Wallet",
	"ojbcfhjmpigfobfclfflafhblgemeidi": "Glow - Solana Wallet BETA",
	"ojggmchlghnjlapmfbnjholfjkiidbch": "Venom Wallet",
	"omaabbefbmiijedngplfjmnooppbclkk": "Tonkeeper wallet for TON",
	"omgopbgchjlaimceodkldgajioeebhab": "Ellipal Wallet",
	"onhogfjeacnfoofkfgppdlbmlmnplgbn": "SubWallet - Polkadot Wallet",
	"ookjlbkiijinhpmnjffcofjonbfbgaoc": "Temple - Tezos Wallet",
	"opcgpfmipidbgpenhmajoajpbobppdil": "Sui Wallet",
	"opfgelmcmbiajamepnmloijbpoleiama": "Rainbow",
	"panpgppehdchfphcigocleabcmcgfoca": "Desig Wallet",
	"pcndjhkinnkaohffealmlmhaepkpmgkb": "Meteor Wallet",
	"pdadjkfkgcafgbceimcpbkalnfnepbnk": "KardiaChain Wallet",
	"pdliaogehgdbhbnmkklieghmmjkpigpa": "Bybit Wallet",
	"penjlddjkjgpnkllboccdgccekpkcbin": "OpenMask - TON wallet",
	"pfccjkejcgoppjnllalolplgogenfojk": "Tomo Wallet",
	"pfilbfecknpnlbcioakkpcmkfckpogeg": "ChainX Wallet",
	"pghngobfhkmclhfdbemffnbihphmpcgb": "Pillar Wallet",
	"pgiaagfkgcbnmiiolekcfmljdagdhlcm": "Stargazer Wallet",
	"phkbamefinggmakgklpkljjmgibohnba": "Pontem Crypto Wallet - Eth Sol BTC",
	"pklfcgcfchhcokldoonkijijfpgmjilh": "Halo Wallet",
	"pnlfjmlcjdjgkddecgincndfgegkecke": "Crocobit",
	"pocmplpaccanhmnllbbkpgfliimjljgo": "Slope Wallet",
	"ppbibelpcjmhbdihakflkdcoccbgbkpo": "UniSat Wallet",
	"ppdadbejkmjnefldpcdjhnkpbjkikoip": "ROSE Wallet",
}
